import './js/components/navbar.js';
import './js/components/popular-products.js';
import './js/components/dessert-list.js';
import './js/components/about-us.js';
import './js/components/feedback.js';
import './js/components/faq.js';
import './js/components/product-modal.js';
import './js/components/contact-modal.js';
import './js/components/scroll-top.js';
